In [1]:
"""Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde."""

'Write a function so that the columns of the output matrix are powers of the input\nvector.\nThe order of the powers is determined by the increasing boolean argument. Specifically, when\nincreasing is False, the i-th output column is the input vector raised element-wise to the power\nof N - i - 1.\n\nHINT: Such a matrix with a geometric progression in each row is named for Alexandre-\nTheophile Vandermonde.'

In [2]:
import numpy as np 
x=np.array([1,2,3,4,5]) 
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix) 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [3]:
 #Similar matrix is created using np.vander function in numpy
import numpy as np 
x=np.array([1,2,3,4,5]) 
N=5 
matrix1 = np.vander(x,N,increasing=False) 
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [4]:
"""Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3."""

'Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of\nthe given sequence is defined as follows:\nThe moving average sequence has n-k+1 elements as shown below.\nThe moving averages with k=4 of a ten-value sequence (n=10) is shown below\ni 1 2 3 4 5 6 7 8 9 10\n===== == == == == == == == == == ==\nInput 10 20 30 40 50 60 70 80 90 100\ny1 25 = (10+20+30+40)/4\ny2 35 = (20+30+40+50)/4\ny3 45 = (30+40+50+60)/4\ny4 55 = (40+50+60+70)/4\ny5 65 = (50+60+70+80)/4\ny6 75 = (60+70+80+90)/4\ny7 85 = (70+80+90+100)/4\nThus, the moving average sequence has n-k+1=10-4+1=7 values.\n\nQuestion: Write a function to find moving average in an array over a window:\nTest it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.'

In [19]:
import numpy as np

def moving_average(a, n=3) :
    asum = np.cumsum(a, dtype=float)     #we use np.cumsum to get a cumulative sum of the numbers
    #print(asum)
    asum[n:] = asum[n:] - asum[:-n]      #We are breaking the array as per desired number which is 'n' in our function and subtracting elements to get the desired result 
    #print(asum)
    return asum[n - 1:] / n

a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
a1=np.array(a) #rounding off the results to two digts 
np.array(moving_average(a1,n=3)).round(3) 

array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])

In [20]:
b=[10,20,30,40,50,60,70,80,90,100]
np.array(moving_average(b,n=4))


array([25., 35., 45., 55., 65., 75., 85.])